In [5]:
from sklearn.model_selection import train_test_split
from ucimlrepo import fetch_ucirepo
import numpy as np

In [6]:
dry_bean = fetch_ucirepo(id=602)

X = dry_bean.data.features
y = dry_bean.data.targets
X.head()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRatio,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,Roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923,0.988856,0.958027,0.913358,0.007332,0.003147,0.834222,0.998724
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272751,0.783968,0.984986,0.887034,0.953861,0.006979,0.003564,0.909851,0.998430
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113,0.989559,0.947849,0.908774,0.007244,0.003048,0.825871,0.999066
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681,0.976696,0.903936,0.928329,0.007017,0.003215,0.861794,0.994199
4,30140,620.134,201.847882,190.279279,1.060798,0.333680,30417,195.896503,0.773098,0.990893,0.984877,0.970516,0.006697,0.003665,0.941900,0.999166

In [7]:
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.15, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.15 / 0.85, random_state=42)

In [ ]:
# X_train
# X_test
# X_val

In [11]:
X_train_type = X_train.select_dtypes(include='number')
X_train_type = (X_train_type - X_train_type.mean()) / X_train_type.std()
X_train_type.head()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRatio,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,Roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4
13363,-0.465190,-0.533033,-0.612818,-0.317926,-0.643418,-0.420371,-0.466534,-0.488608,0.542161,0.220001,0.493870,0.607478,0.191583,0.571305,0.581472,0.878929
80,-0.691092,-0.932980,-1.164793,-0.270528,-1.710513,-2.646503,-0.693919,-0.819438,0.654235,0.637351,1.471875,2.073308,0.120863,2.265158,2.195118,1.018590
12110,-0.685349,-0.827366,-0.656859,-0.938288,0.260600,0.477558,-0.688533,-0.810638,1.459513,0.698880,0.496149,-0.361637,1.253881,0.137490,-0.394229,0.245415
8236,-0.367044,-0.369776,-0.342029,-0.364816,-0.075211,0.199220,-0.370099,-0.353533,-0.692062,0.423970,0.163897,-0.026774,0.270866,0.006471,-0.065294,0.448211
9572,-0.140214,-0.134256,-0.036037,-0.101303,0.081619,0.335744,-0.146507,-0.057825,0.156539,0.714130,0.452016,-0.202133,-0.076196,-0.302717,-0.238629,-0.215369